base:
  project: diabetes-prediction-project
  random_state: 22
  target_col: Outcome

data_source:
  original_source: source_data/diabetes.csv

load_data:
  raw_dataset_csv: data/raw/diabetes.csv

split_data:
  train_path: data/processed/train_diabetes.csv
  test_path: data/processed/test_diabetes.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.5
      l1_ratio: 0.5
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet_regression
  run_name: mlops
  registered_model_name: ElasticNetDiabetesModel
  remote_server_uri: http://127.0.0.1:5000/
